### ISSUE TITLE
圈x 彩云天气导致天气APP不可用

### ISSUE THREAD

**Issue by yaoyanchen** [Peng-YM/QuanX#104]
系统版本： iOS16.0
![IMG_0849](https://user-images.githubusercontent.com/61932075/190572828-05f9fbee-ae0a-4ba5-ae03-e11b7939ee11.PNG)
如图  只设置一个地址也是一样的

**Comment by Peng-YM** [comment]
iOS 16 限制了mitm，请停止使用彩云天气的定位脚本
