### ISSUE TITLE
彩云天气经纬度问题

### ISSUE THREAD

**Issue by novgniy** [Peng-YM/QuanX#105]
经纬度问题

**Comment by novgniy** [comment]
![AB4D9EE3-5C27-483A-955B-2B356FE1B3BB](https://user-images.githubusercontent.com/91649103/201312202-39ce9130-16ca-4883-8ea5-05102d7f506b.png)

**Comment by YangZhaocool** [comment]
彩云的api取消了免费次数 此issues关闭
![image](https://github.com/Peng-YM/QuanX/assets/31984495/d7da9563-f3db-4ff5-b605-1693ddbd584d)
