### ISSUE TITLE
彩云天气定位

### ISSUE THREAD

**Issue by SeanZheng11** [Peng-YM/QuanX#111]
IOS 16.3.1
添加自动定位配置后 打开天气app无法显示
检查surge请求日志显示weather-data.apple.com 的MitM失败。
是不是已经不能使用了？

**Comment by ken4888** [comment]
同问

**Comment by Peng-YM** [comment]
是的，iOS 16 下苹果已经禁止对此域名进行 MITM，目前暂时无解
