### ISSUE TITLE
surge开启脚本转换后本地模块失效

### ISSUE THREAD

**Issue by ch634421335** [Peng-YM/QuanX#17]
开启后本地的模块无法正常工作
测试的有 哔哩哔哩Pro By nzw9314 抖音去水印均无效

**Comment by Peng-YM** [comment]
脚本链接发一下

**Comment by ch634421335** [comment]
https://raw.githubusercontent.com/nzw9314/Surge/master/Module/Script_All_in_one.sgmodule
直接用在线的也会失效

**Comment by Peng-YM** [comment]
目前大部分脚本都已经适配多平台，基本无需转换器了
