### ISSUE TITLE
彩云天气JSON解析

### ISSUE THREAD

**Issue by lbwstco** [Peng-YM/QuanX#23]
![EAD651E3-A3CA-4C99-AB33-8F279088769D](https://user-images.githubusercontent.com/6779378/89844756-18cbf180-dbaf-11ea-8389-659021d84a1e.png)
在boxjs中运行 会一直报这个错

**Comment by Peng-YM** [comment]
本机运行是否会出现这种情况呢？

**Comment by lbwstco** [comment]
> 本机运行是否会出现这种情况呢？

正常运行没有出现这个情况

**Comment by lbwstco** [comment]
刚刚试了下，无法复现了。。先关了
