### ISSUE TITLE
iOS 13.5版本在根据教程填好相关信息后出错（QX）

### ISSUE THREAD

**Issue by weijhao** [Peng-YM/QuanX#28]
![image](https://user-images.githubusercontent.com/70306815/91382598-06b3a980-e865-11ea-8fbf-575caf43382e.png)
![image](https://user-images.githubusercontent.com/70306815/91382612-0d422100-e865-11ea-9c96-1eff5121ed74.png)
![image](https://user-images.githubusercontent.com/70306815/91382617-10d5a800-e865-11ea-8682-cac8fbd08cfb.png)
![image](https://user-images.githubusercontent.com/70306815/91382622-13380200-e865-11ea-9a35-b01a836852d6.png)
![image](https://user-images.githubusercontent.com/70306815/91382629-17641f80-e865-11ea-942e-dda3577f404b.png)
![image](https://user-images.githubusercontent.com/70306815/91382639-1b903d00-e865-11ea-839b-7697540b0c38.png)
（我截图的彩云天气API是个例子，我填的是我自己的token字段）

我申请了彩云的API，按照教程操作，但是到了进入系统天气的这一步，没有提示获取了定位。我点击执行脚本，提示错误

我依据此教程进行配置，
https://github.com/chiupam/tutorial/tree/master/caiyun

相关问题已在
https://t.me/c/1446927138/624715
https://t.me/cool_scripts/78
反馈

https://t.me/c/1446927138/624760
𝒀𝑴 𝑷𝑬𝑵𝑮大佬已答复有时间处理

版本信息-iOS 13.5 QUANTUMULT X v1.0.13-build355 从美区商店购买 蓝色标记

此issues为存档，以备使用。

**Comment by Peng-YM** [comment]
请问配置好重写之后，打开天气应用。再打开boxjs是否能看到当前的经纬度呢

**Comment by weijhao** [comment]
> 请问配置好重写之后，打开天气应用。再打开boxjs是否能看到当前的经纬度呢

不可以的，以下是相关截图，请您参考
![image](https://user-images.githubusercontent.com/70306815/91420521-c7e71900-e88f-11ea-8ce0-ebb2a871cc2a.png)
![image](https://user-images.githubusercontent.com/70306815/91420538-cb7aa000-e88f-11ea-85f9-9472c24c4b3e.png)
![image](https://user-images.githubusercontent.com/70306815/91420546-ce759080-e88f-11ea-9174-a9606714c1d1.png)

**Comment by weijhao** [comment]
您好，刚刚我重新删除了此前设置，开始重新设置后，可以正常获取天气数据，但定位数据反馈是周边城市。

**Comment by Peng-YM** [comment]
目前应该没有办法做到多个地区推送天气。因为获取到的是当前的位置信息。

**Comment by Peng-YM** [comment]
系统天气里面只能保留当前位置的天气，否则会定位出错

**Comment by weijhao** [comment]
> 系统天气里面只能保留当前位置的天气，否则会定位出错

好的，目前我因为定位精准度偏差的原因，我禁用了MITM，并在https://lbs.qq.com/tool/getpoint/index.html获取了经纬度，填写了经纬度，在“应用”页面长按刷新了BoxJs后，得到正确地址的预报信息。

感谢大佬帮助！！
