### ISSUE TITLE
彩云天气脚本

### ISSUE THREAD

**Issue by SilenceJoyson** [Peng-YM/QuanX#29]
我想问一下彩云天气的怎么自定义经纬度  他获取的经纬度不太准确 我想自己填写

**Comment by SilenceJoyson** [comment]
我看上面写关闭mitm可以手动填写  但是我把hostname=weather-data.apple.com, api.weather.com这两个删除后填写别的经纬度  发现显示的地址名字还是原来的  但是天气内容变了  这不知道是不是一个bug

**Comment by Peng-YM** [comment]
不是bug，目前经纬度查询地址使用了缓存，30分钟更新一次。正常使用不会有影响

**Comment by SilenceJoyson** [comment]
好的   谢谢大佬
