### ISSUE TITLE
彩云天气脚本导致Apple Watch的天气无法正常加载数据

### ISSUE THREAD

**Issue by hououinkami** [Peng-YM/QuanX#30]
启用该脚本后，Apple Watch的原生天气无法正常下载天气数据，关闭后正常，请问有办法解决吗？谢谢！

**Comment by Peng-YM** [comment]
请问是最新版本么？哪个App出现的问题

**Comment by hououinkami** [comment]
> 请问是最新版本的彩云么？哪个App出现的问题

我没有单独装彩云的app，出问题的是Apple Watch上的Apple自带的原生天气App，启用脚本时就无法获取到数据，但手机上的自带天气app却正常

**Comment by Peng-YM** [comment]
最新版本的彩云脚本

**Comment by hououinkami** [comment]
Boxjs里更新的之后不就是最新的了？

**Comment by Peng-YM** [comment]
更新脚本

**Comment by hououinkami** [comment]
更新过了，也重启了QuanX，依然不行
