### ISSUE TITLE
彩云天气脚本执行后，出现“❌出现错误”的提示

### ISSUE THREAD

**Issue by xiazhijueju** [Peng-YM/QuanX#33]
虽然没有获取位置成功的提示，不过Boxjs里已经显示经纬度数字，然而点击脚本执行之后，通知上会显示错误的提示。请问是哪里出了问题？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Peng-YM** [comment]
可能是彩云的Token填写错误

**Comment by xiazhijueju** [comment]
我用的是腾讯的Token，Token是不有时效性？

**Comment by Peng-YM** [comment]
腾讯和彩云两个token都需要填写

**Comment by xiazhijueju** [comment]
好的，谢谢

**Comment by xiazhijueju** [comment]
> 腾讯和彩云两个token都需要填写

彩云token还没申请下来，这两天脚本通知忽然显示正常，却同时又有一条如同之前一样的错误通知。
