### ISSUE TITLE
steam手动执行脚本没有任何的反应

### ISSUE THREAD

**Issue by xiazhijueju** [Peng-YM/QuanX#34]
steam价格监控增加更多的内容后，手动执行脚本没有出现通知，内容格式完全按照前面三项样式增加的，检查过未有发现错误之处。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Peng-YM** [comment]
测试正常使用，请检查配置。反馈Bug建议截图BoxJS配置和日志输出

**Comment by xiazhijueju** [comment]
![image](https://user-images.githubusercontent.com/42618989/93429627-06527f80-f8f4-11ea-8ac2-3eda60c356ff.png)

**Comment by xiazhijueju** [comment]
不管是⭕️X还是loon，只要是增加内容，脚本执行都会无效。但如果只是将原本默认的三项内容修改为别的游戏ID和名字，都是正常的。是不是大佬的这个脚本原本就是不能多增加额外的游戏项？

**Comment by xiazhijueju** [comment]
原来是原生输入法双引号的错误，谢谢大佬的指点。
