### ISSUE TITLE
在BOXJS页面内，使用机场流量脚本, 相关配置后点击保存设置，在Surge 脚本选项下没有看到同步过来的脚本？

### ISSUE THREAD

**Issue by zfkira** [Peng-YM/QuanX#35]
Hi 作者你好，

在配好模块，访问Boxjs网页时，点击机场流量， 输入相对应的订阅地址，名称后,点击保存设置，回到Surge 软件->脚本选项下并没有看到同步过来的脚本？请问这是什么问题呢？谢谢！

**Comment by Peng-YM** [comment]
BoxJS本来就没有同步脚本的功能
