### ISSUE TITLE
github监控脚本执行后，无任何结果。

### ISSUE THREAD

**Issue by chenyz1984** [Peng-YM/QuanX#42]
github监控，通过QuanX构造请求和BoxJs执行脚本均无任何反应：
![35ad786e57b2e5dede70f6dac83e6a5](https://user-images.githubusercontent.com/20869868/96965308-82b52f80-153e-11eb-917d-bbf50764282a.jpg)
![52af1b19f226218cd3104d090c08184](https://user-images.githubusercontent.com/20869868/96965318-85b02000-153e-11eb-9ba8-c8ed844f58dd.jpg)

BoxJs的仓库地址如下：
`[
  {
    "name": "NZW9314 脚本",
    "url": "https://github.com/nzw9314/QuantumultX/tree/master"
  },
  {
    "name": "Chavy 脚本",
    "url": "https://github.com/chavyleung/scripts"
  },
  {
    "name": "NobyDa",
    "file_names": ["JD-DailyBonus/JD_DailyBonus.js", "52pojie-DailyBonus"],
    "url": "https://github.com/NobyDa/Script/tree/master"
  }
]`
github token默认

**Comment by Peng-YM** [comment]
多次执行无日志属于正常现象，监控的仓库有更新的时候才会通知提醒

**Comment by chenyz1984** [comment]
> 多次执行无日志属于正常现象，监控的仓库有更新的时候才会通知提醒

多谢回复！
