### ISSUE TITLE
关于申请GitHub需要√什么

### ISSUE THREAD

**Issue by Hello-XPH** [Peng-YM/QuanX#45]
![image](https://user-images.githubusercontent.com/56664327/97958885-1a413a80-1de9-11eb-9c6b-fb37f4203ae3.png)
@Peng-YM

**Comment by Peng-YM** [comment]
<img width="762" alt="截屏2020-11-03 16 15 24" src="https://user-images.githubusercontent.com/21050064/97962290-ca19a680-1def-11eb-98f6-7d421fcc3064.png">

**Comment by Peng-YM** [comment]
如图

**Comment by Hello-XPH** [comment]
谢谢
