### ISSUE TITLE
彩云天气脚本167行取得的resp.body有时候会为空字符串，导致解析失败

### ISSUE THREAD

**Issue by doherty88** [Peng-YM/QuanX#49]
不知道其他人有没有遇到这个问题，我用这个脚本有时会出现json解析失败的错误，分析之后发现是167行的resp.body为空，但是多试几次又可能会好了，不知道怎么回事

**Comment by Peng-YM** [comment]
我也遇到了几次这种情况，有点奇怪....应该是彩云的API不稳定

**Comment by lbwstco** [comment]
今天一直是这个问题 @Peng-YM
