### ISSUE TITLE
查询✈️ 流量失效

### ISSUE THREAD

**Issue by tkfanswind** [Peng-YM/QuanX#55]
最新版qx失效了，无任何日志

**Comment by AndrewXiang** [comment]
确实昨晚也发现查询不到，原来不是我一人的特例。。。之前记得还能查到的

**Comment by YangZhaocool** [comment]
bug已修复 更新脚本在看看

**Comment by tkfanswind** [comment]
有多个订阅地址的时候，只能随机报一个机场的流量信息。请帮忙修复

**Comment by YangZhaocool** [comment]
> 有多个订阅地址的时候，只能随机报一个机场的流量信息。请帮忙修复

可能是因为我把回调放到了事件里面导致的 等再有空的吧

**Comment by YangZhaocool** [comment]
> 有多个订阅地址的时候，只能随机报一个机场的流量信息。请帮忙修复

之前的查询是也随机返回一个 还是都返回

**Comment by YangZhaocool** [comment]
> > 前的查询是也随机返回一个 还是都返回
> 
> 之前所有订阅都返回

知道了 定位到问题了  等有功夫修完 会同步在这个issues

**Comment by YangZhaocool** [comment]
代码已更新 更新一下脚本在看看

**Comment by YangZhaocool** [comment]
有问题在另开issues
