### ISSUE TITLE
彩云天气没法获取当前精准位置

### ISSUE THREAD

**Issue by AndrewXiang** [Peng-YM/QuanX#59]

**Comment by ziiilok** [comment]
我这里是surge配置正确无法获取位置，qx正常使用；surge、qx都是最新tf，ios14.3

**Comment by AndrewXiang** [comment]
> 我这里是surge配置正确无法获取位置，qx正常使用；surge、qx都是最新tf，ios14.3
我用的是QX 1.0.18，非tf，iOS14.3。他的位置没法自动获取当前位置，还是获取的是上一次的位置

**Comment by Peng-YM** [comment]
我在Surge和QX都可以正常使用，请检查一下有没有加正确的重写配置（是不是禁用了）

**Comment by ziiilok** [comment]
重新安排商店版本再设置又可以正常了使用
