### ISSUE TITLE
js-converter.js error body.match(pattern)

### ISSUE THREAD

**Issue by langkhach270389** [Peng-YM/QuanX#65]
Hi Dev
Fix if(body.match(pattern) != null)

**Comment by Peng-YM** [comment]
Could you please open a PR?

**Comment by kinghui110** [comment]
{"message":"JSON Parse error: Unexpected EOF","line":167,"column":30,"stack":"parse@[native code]\n\npromiseReactionJob@[native code]"}
大佬，彩云天气经常出现这个问题。怎么解决呢？
