### ISSUE TITLE
使用MITM模块时遇到了一点问题

### ISSUE THREAD

**Issue by a08381** [Peng-YM/QuanX#72]
我在尝试将[这个](https://github.com/Diving-Fish/maimaidx-prober/blob/master/proxy/cmd/maimaidx-prober-proxy/main.go)移植到iOS上，于是想要借助您的mitm模块，但是在使用过程中，我发现我修改了workspace，但是不知道为什么，插件并没有读取我在workspace下面的脚本，所以我想向您请教一下我是不是哪里出了问题

![2021-07-18 12-08-47 的屏幕截图](https://user-images.githubusercontent.com/2505002/126055441-35ebf07d-bfdb-4af7-a848-6b28163af178.png)

代码已上传到https://pastebin.com/iW4fGFvV

![2021-07-18 12-25-36 的屏幕截图](https://user-images.githubusercontent.com/2505002/126055677-09493421-1875-4a3c-850c-2dc6c39a3e85.png)

运行状况如图，开启了debug也没有任何输出。

**Comment by Peng-YM** [comment]
有读取的，第二张图里面有 Log：Added script maimaidx-prober.js

**Comment by a08381** [comment]
> 有读取的，第二张图里面有 Log：Added script maimaidx-prober.js

有显示，但是我加了几次log也没有回复

**Comment by Gowther** [comment]
> > 有读取的，第二张图里面有 Log：Added script maimaidx-prober.js
> 
> 有显示，但是我加了几次log也没有回复，console.log和$.log都试过了，开启了DEBUG也没有详细信息

@a08381 我也碰到同样的问题，终端显示Script test-request-body triggered by http://httpbin.org/post，但没有日志输出，body最终也没有修改，您最后是怎么解决的呢？
