### ISSUE TITLE
彩云天气按教程设置后报错{''error'':''bad url."}

### ISSUE THREAD

**Issue by hechangran** [Peng-YM/QuanX#73]
现象：通知栏显示 
[彩云天气]
 X 出现错误 
{''error'':''bad url."}

设置：彩云api、腾讯api已经设置，经纬度也自动获取了。

请问是因为脚本失效了？还是我的设置有问题？

**Comment by YangZhaocool** [comment]
0.0 这个报错是无效的url  建议检查一下链接

**Comment by YangZhaocool** [comment]
彩云取消了api的免费调用 此issues关闭
![image](https://github.com/Peng-YM/QuanX/assets/31984495/3169e88d-59eb-4fa1-955b-607a01f52c39)
