### ISSUE TITLE
IOS 15下，彩云天气获取位置报错

### ISSUE THREAD

**Issue by askiter** [Peng-YM/QuanX#76]
我升级到IOS15之后，Surge报错如下
正则表达式匹配错误
无法从URL:https://weather-data.apple.com/
v2/availability/39.93/116.33 获取位置。

我看了一下代码，应该是要增加一段匹配规则吧

url.match(/v2/availability\/(.*)\/(.*)\?/) ||

**Comment by Peng-YM** [comment]
已修复
