### ISSUE TITLE
Surge issues in new OpenAPI

### ISSUE THREAD

**Issue by NobyDa** [Peng-YM/QuanX#81]
$surge这个API在Surge环境下很特殊，如果没有指定内部属性它将直接返回undefined，无法用于判断环境；且该API已废弃，建议修改为$utils

https://github.com/Peng-YM/QuanX/blob/3dac956312775881a60260b9cc5e7394f14a5f77/Tools/OpenAPI/API.js#L12

**Comment by Peng-YM** [comment]
感谢大佬告知，好久没有看 change log 了。能不能用 `$utils` 加 `$httpClient` 判断呢？
