### ISSUE TITLE
问题已经解决了

### ISSUE THREAD

**Issue by love499520** [Peng-YM/QuanX#82]
api失效自己折腾了一下，api返回数据货币代码为小写字母时无法正常输出，这个应该怎么处理

**Comment by Peng-YM** [comment]
这个脚本我已经好久没有搞了，修复了可以 PR 一下吗？

**Comment by love499520** [comment]
> 这个脚本我已经好久没有搞了，修复了可以 PR 一下吗？
可以

**Comment by Peng-YM** [comment]
感谢！
