### ISSUE TITLE
能否把一些脚本、模块适配小火箭

### ISSUE THREAD

**Issue by JOJOforshaun** [Peng-YM/QuanX#85]
小火箭和loon、surge在这方面差不多吧

**Comment by Peng-YM** [comment]
小火箭直接用Surge的写法就可以

**Comment by JOJOforshaun** [comment]
> 小火箭直接用Surge的写法就可以

可是我这样在小火箭里配置无法运行脚本，19:32根本没有触发脚本，手动运行也提示超时。我查看小火箭的诊断日志，搜索exchange.js，没有任何记录。
不知道是小火箭的问题还是这个脚本的问题呢

汇率 = type=cron,script-path=https://raw.githubusercontent.com/Peng-YM/QuanX/master/Tasks/exchange.js,cronexpr=32 19 * * *,timeout=10,enable=true

**Comment by YangZhaocool** [comment]
> > 小火箭直接用Surge的写法就可以
> 
> 可是我这样在小火箭里配置无法运行脚本，19:32根本没有触发脚本，手动运行也提示超时。我查看小火箭的诊断日志，搜索exchange.js，没有任何记录。 不知道是小火箭的问题还是这个脚本的问题呢
> 
> 汇率 = type=cron,script-path=https://raw.githubusercontent.com/Peng-YM/QuanX/master/Tasks/exchange.js,cronexpr=32 19 * * *,timeout=10,enable=true
看了代码 这个脚本的接口失效了 等等吧

**Comment by YangZhaocool** [comment]
> > 小火箭直接用Surge的写法就可以
> 
> 可是我这样在小火箭里配置无法运行脚本，19:32根本没有触发脚本，手动运行也提示超时。我查看小火箭的诊断日志，搜索exchange.js，没有任何记录。 不知道是小火箭的问题还是这个脚本的问题呢
> 
> 汇率 = type=cron,script-path=https://raw.githubusercontent.com/Peng-YM/QuanX/master/Tasks/exchange.js,cronexpr=32 19 * * *,timeout=10,enable=true

汇率接口已替换 再看看

**Comment by JOJOforshaun** [comment]
> 

谢谢大佬 可以了

**Comment by YangZhaocool** [comment]
那先关闭 有其他问题在另开issues
