### ISSUE TITLE
关于机场流量查询

### ISSUE THREAD

**Issue by YangZhaocool** [Peng-YM/QuanX#96]
机场流量得真正的佬修复了
暂时先建议  圈x：在订阅节点的时候添加后缀#info=1，并开启资源管理器
                    其他平台没有建议0.0

**Comment by Peng-YM** [comment]
这个逻辑没有依赖第三方 API，只要机场支持流量信息应该就没有问题的

**Comment by YangZhaocool** [comment]
我还不理解圈x的运行逻辑 我这的机场 如果在订阅链接的时候添加后缀那种是可以正常返回信息的 但是用脚本没有数据 不清楚到底是哪的问题 0.0

**Comment by YangZhaocool** [comment]
知道问题了 一会就push
